/*
 * Copyright (C) 2010, Freescale Semiconductor, Inc. All Rights Reserved.
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
 *
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("updater.sb")]
        public string UpdaterFilename {
            get {
                return ((string)(this["UpdaterFilename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1647")]
        public ushort MscUsbVid {
            get {
                return ((ushort)(this["MscUsbVid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40976")]
        public ushort MscUsbPid {
            get {
                return ((ushort)(this["MscUsbPid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1647")]
        public ushort MtpUsbVid {
            get {
                return ((ushort)(this["MtpUsbVid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40976")]
        public ushort MtpUsbPid {
            get {
                return ((ushort)(this["MtpUsbPid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1647")]
        public ushort UpdaterUsbVid {
            get {
                return ((ushort)(this["UpdaterUsbVid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14335")]
        public ushort UpdaterUsbPid {
            get {
                return ((ushort)(this["UpdaterUsbPid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1647")]
        public ushort RecoveryUsbVid {
            get {
                return ((ushort)(this["RecoveryUsbVid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14080")]
        public ushort RecoveryUsbPid {
            get {
                return ((ushort)(this["RecoveryUsbPid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EraseMedia {
            get {
                return ((bool)(this["EraseMedia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreserveJanus {
            get {
                return ((bool)(this["PreserveJanus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FSL MMC")]
        public string VolumeLabel {
            get {
                return ((string)(this["VolumeLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLog {
            get {
                return ((bool)(this["ShowLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                 <ArrayOfLogicalDrive xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                    <!--- type: Data, HiddenData, System -->
                    <!--- tag: FirmwareImg, FirmwareImg2, FirmwareImg3, Data, DataJanus, DataSettings, tData, tJanus, tSettings -->
                    <!--- type: None, ImageData, Format, JanusInit, FileData -->
                    <LogicalDrive filename=""firmware.sb"" desc=""Firmware Image 1"" type=""System"" tag=""FirmwareImg"" requestedSize=""0"" flags=""ImageData"" />
                    <LogicalDrive desc=""Data Drive"" type=""Data"" tag=""tData"" requestedSize=""0"" flags=""Format"" />
                    <LogicalDrive desc=""Janus Drive"" type=""HiddenData"" tag=""tJanus"" requestedSize=""0"" flags=""JanusInit"" />
                    <LogicalDrive desc=""Settings Drive"" type=""HiddenData"" tag=""tSettings"" requestedSize=""0"" flags=""None"" />
                    <LogicalDrive filename=""firmware.sb"" desc=""Firmware Image 2"" type=""System"" tag=""FirmwareImg2"" requestedSize=""0"" flags=""ImageData"" />
                    <LogicalDrive filename=""firmware.sb"" desc=""Firmware Image 3"" type=""System"" tag=""FirmwareImg3"" requestedSize=""0"" flags=""ImageData"" />
                 </ArrayOfLogicalDrive>
              ")]
        public DevSupport.Media.LogicalDrive[] DriveArray {
            get {
                return ((DevSupport.Media.LogicalDrive[])(this["DriveArray"]));
            }
        }
    }
}
