//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StMfgTool.rc
//
#define IDS_EXIT                        2
#define IDC_IPEDIT                      3
#define ID_SAVE_BUTTON                  4
#define IDB_COMPANY_BMP                 100
#define IDP_OLE_INIT_FAILED             101
#define IDI_UPDATER_ICON                102
#define IDD_LOGMGR_DIALOG               103
#define IDI_COMPANY_ICON                104
#define IDI_COMPANY_BMP                 109
#define IDI_CUSTOM_COMPANY_BMP          110
#define IDR_MAINFRAME                   128
#define IDR_StMfgToolTYPE               129
#define IDD_BUTTON_DLG                  130
#define IDD_PORT_DLG                    131
#define IDD_CONF_GENERAL_DLG            132
#define IDD_CONF_USB_PORT_DLG           133
#define IDD_CONF_PROFILE_DLG            134
#define IDD_CONF_OP_DETAILS_DLG         135
#define IDD_REGSCRUB_DLG                138
#define IDB_USB_STATE                   139
#define IDD_REGISTRY_DLG                140
#define IDB_OP_STATE                    141
#define IDD_CONF_OP_EDIT_DLG            142
#define IDD_DIALOG1                     145
#define IDD_EDIT_DRIVE                  145
#define IDD_FILEOPDLG                   146
#define IDD_COPYOPDLG                   146
#define IDD_UPDATEOPDLG                 147
#define IDR_UPDATELIST_MENU             148
#define IDD_LOADOPDLG                   149
#define IDD_OTPOPDLG                    150
#define IDR_BOUND_LANG_IDS              150
#define IDR_BOUND_RESOURCE_COUNT        151
#define IDB_OPEN_FOLDER                 152
#define IDR_BOUND_LANG_RESOURCE_COUNT   152
#define IDD_REGCHECK_DLG                153
#define IDR_BOUND_RESOURCE_TABLE        153
#define IDR_BOUND_RESOURCE_TABLE_LEN    154
#define IDR_USE_LOCAL_RESOURCES         155
#define IDD_MXUPDATEOPDLG               155
#define IDR_DEFAULT_DIALOG              156
#define IDD_UTPUPDATEOPDLG              156
#define IDD_CONF_PROFILE_DLG2           157
#define IDR_STMP3REC_SYS                160
#define IDR_STMP3REC_INF                161
#define IDR_STMP3REC_CAT                162
#define IDR_STMP3RECX64_SYS             163
#define IDR_STMP3RECX64_INF             164
#define IDR_STMP3RECX64_CAT             165
#define IDR_CFG_ALWAYS_FORCE_RECOVERY   170
#define IDR_CFG_ERASE_MEDIA             171
#define IDR_CFG_FORMAT_DATA             172
#define IDR_CFG_VERSION                 173
#define IDR_CFG_COMPANYNAME             174
#define IDR_CFG_PRODUCTDESC             175
#define IDR_CFG_PRODUCTNAME             176
#define IDR_CFG_APPTITLE                177
#define IDR_CFG_COPYRIGHT               178
#define IDR_CFG_COMMENTS                179
#define IDR_CFG_SCSIMFG                 180
#define IDR_CFG_SCSIPROD                181
#define IDR_CFG_MTPMFG                  182
#define IDR_CFG_MTPPROD                 183
#define IDR_CFG_USBVENDOR               184
#define IDR_CFG_USBPROD                 185
#define IDR_CFG_AUTORECOVERY            186
#define IDR_CFG_FORCERECOVERY           187
#define IDR_CFG_USELOCALRES             188
#define IDR_CFG_WINCE                   189
#define IDR_CFG_DLGTYPE                 190
#define IDR_CFG_FORMATDATA              191
#define IDR_CFG_ERASEMEDIA              192
#define IDR_CFG_DEFAULTFAT              193
#define IDR_CFG_DEFAULTLABEL            194
#define IDR_CFG_REBOOTMSG               195
#define IDR_CFG_ABOUT_BMP               196
#define IDR_CFG_BASE_SDK                197
#define IDR_CFG_LOW_NAND_SOLUTION       198
#define IDR_CFG_AUTOSTART               199
#define IDR_CFG_AUTOCLOSE               200
#define IDR_CFG_BITMAP_ID               201
#define IDR_CFG_MINDLG_FMT_MSG          202
#define IDR_CFG_USBPROD_SECONDARY       203
#define IDR_CFG_UPD_MAJOR_VERSION       250
#define IDR_CFG_UPD_MINOR_VERSION       251
#define IDR_CFG_PROD_MAJOR_VERSION      252
#define IDR_CFG_PROD_MINOR_VERSION      253
#define IDR_CFG_DRVARRAY_NUM_DRIVES     300
#define IDR_CFG_DRVARRAY_ONE            301
#define IDR_CFG_DRVARRAY_TWO            302
#define IDR_CFG_DRVARRAY_THREE          303
#define IDR_CFG_DRVARRAY_FOUR           304
#define IDR_CFG_DRVARRAY_FIVE           305
#define IDR_CFG_DRVARRAY_SIX            306
#define IDR_CFG_DRVARRAY_SEVEN          307
#define IDR_CFG_DRVARRAY_EIGHT          308
#define IDR_CFG_DRVARRAY_NINE           309
#define IDR_CFG_DRVARRAY_TEN            310
#define IDR_CFG_DRVARRAY_ELEVEN         311
#define IDR_CFG_DRVARRAY_TWELVE         312
#define IDR_CFG_DRVARRAY_THIRTEEN       313
#define IDR_CFG_DRVARRAY_FOURTEEN       314
#define IDR_CFG_DRVARRAY_FIFTEEN        315
#define ID_PORT_GROUP_BOX               1001
#define IDC_PORT_PROGRESS               1002
#define IDC_LOG_DATA                    1003
#define IDC_PORT_DRIVE                  1004
#define IDC_PORT_STATUS_EDIT            1005
#define IDC_PORT_DRIVE_TEXT             1006
#define IDC_CLN_REG_CHECK               1007
#define IDC_LANGUAGE_COMBO              1008
#define IDC_SUPRESS_AUTOPLAY            1009
#define IDC_USB_TREE                    1010
#define IDC_PLAYER_PROFILE_COMBO        1011
#define IDC_PART_TEXT                   1012
#define IDC_OPERATION_DESC_TEXT         1013
#define IDC_OPERATION_COMBO             1014
#define IDC_USB_VID_TEXT                1015
#define IDC_USB_PID_TEXT                1016
#define IDC_SCSI_MFG_TEXT               1017
#define IDC_SCSI_PRODUCT_TEXT           1018
#define IDC_FIRMWARE_TEXT               1019
#define IDC_FIRMWARE_BROWSE             1020
#define IDC_NEW                         1021
#define IDC_EDIT                        1022
#define IDC_DELETE                      1023
#define IDC_PRODUCT_TEXT                1024
#define IDC_PLAYER_PROFILE_EDIT         1025
#define IDC_PART_DESC_TEXT              1026
#define IDC_PART_COMBO                  1027
#define IDC_PROCESS_STEP_DESC_TEXT      1028
#define IDC_USB_VID_DESC_TEXT           1029
#define IDC_USB_VID_EDIT                1030
#define IDC_USB_PID_DESC_TEXT           1031
#define IDC_USB_PID_EDIT                1032
#define IDC_VOLUME_LABEL_DESC_TEXT      1032
#define IDC_SCSI_MFG_DESC_TEXT          1033
#define IDC_SCSI_VID_EDIT               1034
#define IDC_SCSI_PRODUCT_DESC_TEXT      1035
#define IDC_SCSI_PID_EDIT               1036
#define IDC_FIRMWARE_DESC_TEXT          1037
#define IDC_FIRMWARE_EDIT               1038
#define IDC_CURRENT_PROFILE_CHECK       1039
#define IDAPPLY                         1040
#define IDC_WIZARD                      1041
#define IDC_OPLIST_EDIT                 1042
#define IDC_OPERATIONS_LIST             1043
#define IDC_STATUS_ICON                 1044
#define IDC_STATUS_TEXT                 1045
#define IDC_OPLIST_BROWSE_BUTTON        1046
#define IDC_OPLIST_COMBO                1047
#define IDC_ABOUT_VERSION_TEXT          1048
#define IDC_ABOUT_COPYRIGHT_TEXT        1049
#define IDC_AUTOPLAY_DRV_COMBO          1050
#define IDC_AUTOPLAY_ALL_DRVS_RADIO     1051
#define IDC_AUTOPLAY_SEL_DRVS_RADIO     1052
#define IDC_IDC_AUTOPLAY_DRV_LIST       1053
#define IDC_CLEAR_ERROR_BUTTON          1054
#define IDC_PORT_OPERATION_TEXT         1055
#define IDC_PORT_TASK_PROGRESS          1056
#define IDC_RESTRICT_DEVICE_CHECK       1057
#define IDC_USE_STATIC_REC_FW_CHECK     1058
#define IDC_REG_DELETING                1059
#define IDC_REG_DEVICE_COUNT            1060
#define IDC_REG_PROCESSING              1061
#define IDC_VOLUME_LABEL_TEXT           1062
#define IDC_OPERATION_TEXT              1063
#define IDC_DIRECTORY_TEXT              1064
#define IDC_FILES_TEXT                  1065
#define IDC_DEST_DIR_TEXT               1066
#define IDC_SRC_DIR_EDIT                1067
#define IDC_DEST_DIR_EDIT               1068
#define IDC_OP_NAME_TEXT                1069
#define IDC_OPERATION_EDIT              1070
#define IDC_FILES_BROWSE_BUTTON         1071
#define IDC_OPTIONS_LIST                1072
#define IDC_REMOVE_STATIC_IDS           1073
#define IDC_EVENT_LOG_ENABLE_CHECK      1073
#define IDC_VOLUME_LABEL_CHECK          1074
#define IDC_FILE_LIST                   1075
#define IDC_BROWSE_TREE                 1076
#define IDC_ADD_ALL_BUTTON              1077
#define IDC_REMOVE_BUTTON               1078
#define IDC_ADD_BUTTON                  1079
#define IDC_REMOVE_ALL_BUTTON           1080
#define IDC_FILE_TYPE_COMBO             1081
#define IDC_OP_NAME_EDIT                1082
#define IDC_LIST1                       1083
#define IDC_IMAGE_LIST                  1083
#define IDC_DRIVE_LIST                  1083
#define IDC_OP_OPTIONS_LIST             1084
#define IDC_OP_PATH_EDIT                1085
#define IDC_STEP1_GROUP                 1086
#define IDC_STEP2_GROUP                 1087
#define IDC_STEP3_GROUP                 1088
#define IDC_SRC_DIR_TEXT                1089
#define IDC_STEP2_GROUP2                1089
#define IDC_FILE_TYPE_TEXT              1090
#define IDC_STEP4_GROUP                 1091
#define IDC_STEP1_TEXT                  1092
#define IDC_STEP2_TEXT                  1093
#define IDC_STEP3_TEXT                  1094
#define IDC_STEP4_TEXT                  1095
#define IDC_OP_TYPE_TEXT                1096
#define IDC_OP_TYPE_COMBO               1097
#define IDC_OP_FILE_LIST                1098
#define IDC_SCRUB                       1101
#define IDC_PLAYER_PROFILE_TEXT         1102
#define IDC_OPTIONS_TEXT                1103
#define IDC_OPERATION_STATUS_TEXT       1104
#define IDC_PROFILE_COMBO               1104
#define IDC_DIRECTORY_EDIT              1105
#define IDC_USBMSC_UPDATE_RADIO         1105
#define IDC_FILES_EDIT                  1106
#define IDC_MTP_UPDATE_RADIO            1106
#define IDC_OPERATIONS_COMBO            1107
#define IDC_UPDATE_RADIO                1107
#define IDC_BUTTON1                     1113
#define IDC_OP_FILE_ADVANCED_BUTTON     1113
#define IDC_ADD_DRIVE                   1113
#define IDC_BROWSE_FILE                 1114
#define IDC_EDIT_FILE_NAME              1115
#define IDC_EDIT_DESCRIPTION            1118
#define IDC_COMBO_DRIVE_TYPE            1119
#define IDC_EDIT_DRIVE_TAG              1120
#define IDC_EDIT_REQUESTED_DRIVE_SIZE   1122
#define IDC_SDK_BASE_COMBO              1123
#define IDC_COMBO_SDK_BASE              1124
#define IDC_HOTKEY1                     1125
#define IDC_EDIT_DATA_DRIVE_NUM         1126
#define IDC_STATIC_DRIVE_NUM_EDIT_LABEL 1127
#define IDC_OP_COUNT                    1128
#define IDC_SCANNING_TEXT               1129
#define IDC_STATUS_PROFILE_COMBO        1129
#define IDC_USBPORTS_ENABLED_PORTS      1129
#define IDC_GENERAL_ACTIVE_PORTS_TEXT   1130
#define IDC_PLAYER_PROIFLE_SELECT_TEXT  1130
#define IDC_OP_TIMEOUT_TEXT             1130
#define IDC_DELETING_TEXT               1131
#define IDC_USBPORT_ACTIVEPORTS_TEXT    1131
#define IDC_USBPORTS_PORTS_ENABLED_TEXT 1131
#define IDC_EDIT1                       1131
#define IDC_NUM_DRIVE_COPIES            1131
#define IDC_OP_LOAD_FNAME_EDIT          1131
#define IDC_STATUS                      1132
#define IDC_NUM_DRIVE_COPIES_TEXT       1132
#define IDC_OP_TIMEOUT_EDIT             1132
#define IDC_REMOVED_TEXT                1133
#define IDC_UPDATE_STEP2_TEXT           1133
#define IDC_UPDATE_STEP3_TEXT           1134
#define IDC_UPDATE_STEP1_TEXT           1135
#define IDC_COMBO_DRIVE_TAG             1136
#define IDC_OP_FOLDERTREE               1137
#define IDC_OP_COPY_DRV_NUM_COMBO       1138
#define IDC_OP_COPY_NUMOBJECTS          1139
#define IDC_REMOVE_RECOVERY_ENTRIES     1140
#define IDC_OTPOP_VALUE                 1140
#define IDC_OTPOP_TEXT                  1141
#define IDC_REGCHK_PROGRESS             1142
#define IDC_REGCHK_INFO_TEXT            1143
#define IDC_REGCHK_ENTRIES_TEXT         1144
#define IDC_REGCHK_ENTRIES              1145
#define IDC_REGCHK_OTHER_DEVICES_TEXT   1146
#define IDC_REGCHK_OTHER_ENTRIES        1147
#define IDC_UCL_FNAME_EDIT              1148
#define IDC_UCL_BROWSE_BTN              1149
#define IDC_STATUS_GRP_TEXT             1150
#define IDC_RKL_FNAME_EDIT              1150
#define IDC_STATUS_PROFILE_TEXT         1151
#define IDC_OP_MX_UPDATE_IMAGE_LIST_TEXT2 1151
#define IDC_STATUS_PROFILE              1152
#define IDC_IMAGE_FILES_BROWSE_BTN      1152
#define IDC_STATUS_VIDPID_TEXT          1153
#define IDC_RKL_BROWSE_BTN              1153
#define IDC_STATUS_VIDPID               1154
#define IDC_STATUS_FW_VER_TEXT          1155
#define IDC_STATUS_FW_VER               1156
#define IDC_STATUS_START_TEXT           1157
#define IDC_STATUS_START                1158
#define IDC_STATUS_ELAPSED_TEXT         1159
#define IDC_STATUS_ELAPSED              1160
#define IDC_STATUS_AVG_DURATION_TEXT    1161
#define IDC_STATUS_AVG_DURATION         1162
#define IDC_STATUS_OK_UPDATES_TEXT      1163
#define IDC_STATUS_OK_UPDATES           1164
#define IDC_STATUS_FAILED_UPDATES_TEXT  1165
#define IDC_STATUS_FAILED_UPDATES       1166
#define IDC_STATUS_FAILURE_RATE_TEXT    1167
#define IDC_STATUS_FAILURE_RATE         1168
#define IDC_STATUS_STATUS_TEXT          1169
#define IDC_STATUS_STATUS               1170
#define IDC_HUB_REQUIRED                1171
#define IDC_UPDATE_BOOT_FW_BROWSE_BTN   1172
#define IDC_UPDATE_BOOT_FW_EDIT         1173
#define IDC_UPDATE_STEP4_TEXT           1174
#define IDC_REQUIRED_FILES_BROWSE_BTN   1174
#define IDC_STATUS_MULTI_COMBO_PROFILE  1175
#define IDC_STATUS_MULTI_COMBO_SETTINGS 1176
#define IDC_ABOUT_ALLRIGHTS_TEXT        1177
#define IDC_CFG_COM_PORT_MSGS           1178
#define IDC_OP_UTP_UPDATE_UCL_LIST_COMBO 1179
#define IDC_OP_UTP_UPDATE_UCL_LIST_TEXT 1180
#define IDC_OP_UTP_UPDATE_UCL_LIST_TEXT2 1181
#define IDS_PLAYER_INI                  2999
#define IDS_OPINFO_ERR_NOT_INITIALIZED  3000
#define IDS_OPINFO_ERR_MISSING_DIRECTORY 3001
#define IDS_OPINFO_ERR_EMPTY_DIRECTORY  3002
#define IDS_OPINFO_ERR_MISSING_INI_SECTION 3003
#define IDS_OPINFO_ERR_MISSING_FILE     3004
#define IDS_OPINFO_ERR_INVALID_OPERATION 3005
#define IDS_OPINFO_ERR_SYSTEM_ERROR     3006
#define IDS_OPINFO_ERR_NO_CMD_LINE      3007
#define IDS_OPINFO_OK                   3008
#define IDS_OPINFO_ERR_NO_FILE_DESC     3009
#define IDS_OPINFO_ERR_INVALID_DRV_TYPE 3010
#define IDS_OK                          3100
#define IDS_CANCEL                      3101
#define IDS_CLOSE                       3102
#define IDS_ERROR                       3103
#define IDS_NEW                         3104
#define IDS_EDIT                        3105
#define IDS_DELETE                      3106
#define IDS_SAVE                        3107
#define IDS_WAITING_FOR_DEVICE          3108
#define IDS_WAITING_FOR_DRIVE           3109
#define IDS_STOPPED_BY_USER             3110
#define IDS_NO_DEVICE_CONNECTED         3111
#define IDS_RESETTING_DEVICE            3112
#define IDS_STOP                        3120
#define IDS_STOPPING                    3121
#define IDS_START                       3122
#define IDS_VALID_PROFILE_TO_SCRUB      3123
#define IDS_INVALID_PLAYER_PROFILE      3124
#define IDS_STOP_REQUIRED               3125
#define IDS_UNSAFE_DEVICE_REMOVAL       3126
#define IDS_CFG_TITLE                   3130
#define IDS_CFG_FNAME                   3131
#define IDS_CFG_DESC                    3132
#define IDS_CFG_DRIVE_TYPE              3133
#define IDS_CFG_DRIVE_TAG               3134
#define IDS_CFG_DRIVE_SIZE              3135
#define IDS_CFG_DRIVE_GROUP             3136
#define IDS_CFG_ADD_DRIVE               3137
#define IDS_CFG_DRIVES_GROUP            3138
#define IDS_CFG_SDK_BASE                3139
#define IDC_CFG_FNAME_TEXT              3140
#define IDC_CFG_DESC_TEXT               3142
#define IDC_CFG_DRIVE_TYPE_TEXT         3143
#define IDC_CFG_DRIVE_TAG_TEXT          3144
#define IDC_CFG_DRIVE_SIZE_TEXT         3145
#define IDC_CFG_DRIVE_GROUP_TEXT        3146
#define IDC_CFG_DRIVES_GROUP_TEXT       3147
#define IDC_CFG_ADD_DRIVE_TEXT          3148
#define IDC_CFG_SDK_BASE_TEXT           3149
#define IDS_CFG_GENERAL_TITLE           3150
#define IDS_CFG_GENERAL_RESTRICT_DEVICE 3151
#define IDS_CFG_GENERAL_SUPRESS_AUTOPLAY 3152
#define IDS_CFG_GENERAL_AUTOPLAY_ALL_DRVS 3153
#define IDS_CFG_GENERAL_AUTOPLAY_SELECT_DRIVE 3154
#define IDS_CFG_GENERAL_LANGUAGE_GROUP  3155
#define IDS_CFG_GENERAL_OPTIONS_GROUP   3156
#define IDS_CFG_GENERAL_DEFAULT_LANGUAGE 3157
#define IDS_CFG_GENERAL_AUTOPLAY_GROUP  3158
#define IDS_CFG_GENERAL_ENABLE_LOGGING  3159
#define IDC_CFG_GENERAL_LANGUAGE_GROUP_TEXT 3160
#define IDC_CFG_GENERAL_OPTIONS_GROUP_TEXT 3161
#define IDC_CFG_GENERAL_DEFAULT_LANGUAGE_TEXT 3162
#define IDC_CFG_GENERAL_AUTOPLAY_GROUP_TEXT 3163
#define IDS_OP_EDIT_TITLE               3170
#define IDS_OP_EDIT_ADD_FILE            3171
#define IDS_OP_EDIT_ADD_DIR             3172
#define IDS_OP_EDIT_FILE_REMOVE         3173
#define IDS_OP_EDIT_TYPE                3174
#define IDS_OP_EDIT_STEP1               3175
#define IDS_OP_EDIT_NAME_OPERATION      3176
#define IDS_OP_EDIT_NAME                3177
#define IDS_OP_EDIT_SELECT_FILES        3178
#define IDS_OP_EDIT_SELECT_OPTIONS      3179
#define IDS_OP_EDIT_STEP1_GRP           3180
#define IDS_OP_EDIT_STEP2_GRP           3181
#define IDS_OP_EDIT_STEP3_GRP           3182
#define IDS_OP_EDIT_STEP4_GRP           3183
#define IDS_OP_EDIT_ADVANCED            3184
#define IDS_OP_EDIT_DRIVE_NUM           3185
#define IDS_DIRECTORY_DETECTED_PROMPT   3186
#define IDS_DIRECTORY_DETECTED_TITLE    3187
#define IDS_FILE_BROWSE_TYPES           3188
#define IDS_NOTHING_TO_REMOVE           3189
#define IDS_INVALID_OP_FOLDER           3190
#define IDS_OP_ALREADY_EXISTS           3191
#define IDS_CONFIRM_OVERWRITE           3192
#define IDS_SELECT_DIRECTORY            3193
#define IDS_OPTIONS                     3194
#define IDS_NO_OPTIONS                  3195
#define IDS_NO_ITEMS_IN_VIEW            3196
#define IDS_OP_EDIT_TIMEOUT             3197
#define IDS_MENU_ENABLE                 3200
#define IDS_MENU_NEW                    3201
#define IDS_MENU_EDIT                   3202
#define IDS_MENU_DELETE                 3203
#define IDS_MENU_MOVE_UP                3204
#define IDS_MENU_MOVE_DOWN              3205
#define IDS_NEW_DIR                     3206
#define IDS_ERASE_MEDIA                 3207
#define IDS_CFG_PROFILE_TITLE           3210
#define IDS_CFG_PROFILE_LABEL           3211
#define IDS_CFG_PROFILE_DESC            3212
#define IDS_CFG_PROFILE_USB_VENDOR      3213
#define IDS_CFG_PROFILE_USB_PRODUCT     3214
#define IDS_CFG_PROFILE_SCSI_VENDOR     3215
#define IDS_CFG_PROFILE_SCSI_PRODUCT    3216
#define IDS_CFG_PROFILE_OPERATIONS      3217
#define IDS_CFG_PROFILE_GRP             3218
#define IDS_CFG_PROFILE_INVALID_DESC    3219
#define IDS_DELETE_CONFIRM_MSG          3220
#define IDS_DELETE_CONFIRM_TITLE        3221
#define IDS_TOOLTIP_NO_PATH             3222
#define IDS_TOOLTIP_PROFILE_LOCATION    3223
#define IDS_TOOLTIP_NO_FILES            3224
#define IDS_CFG_PROFILE_INVALID_DESC_MSG 3225
#define IDS_CFG_PROFILE_EXISTS_MSG      3226
#define IDS_CFG_PROFILE_COL_OP          3227
#define IDS_CFG_PROFILE_COL_FOLDER      3228
#define IDS_CFG_PROFILE_COL_FILES       3229
#define IDS_CFG_PROFILE_COL_OPTIONS     3230
#define IDS_CFG_PROFILE_DELETE_CONFIRM  3231
#define IDS_CFG_PROFILE_DELETE_TITLE    3232
#define IDC_PROFILE_GRP                 3239
#define IDS_CFG_USBPORT_UNASSIGNED      3240
#define IDS_CFG_USBPORT_PANEL           3241
#define IDS_CFG_USBPORT_PORT            3242
#define IDS_CFG_USBPORT_HUB             3243
#define IDS_CFG_USBPORT_HUB_PORT        3244
#define IDS_CFG_USBPORT_MYCOMPUTER      3245
#define IDS_CFG_USBPORT_CONTROLLER      3246
#define IDS_OPCOPY_COPYING              3250
#define IDS_OPCOPY_STARTED              3251
#define IDS_OPCOPY_COMPLETE             3252
#define IDS_OPCOPY_STOPPED_BY_USER      3253
#define IDS_OPCOPY_FINALIZING_COPY      3254
#define IDS_OPCOPY_CREATING_DIR         3255
#define IDS_OPCOPY_CREATE_DIR_ERR       3256
#define IDS_OPCOPY_COPY_ERR             3257
#define IDS_OPCOPY_COPYING_FILE         3258
#define IDS_ERASEOP_WAITING_DEVICE      3260
#define IDS_ERASEOP_WAITING_DRIVE       3261
#define IDS_ERASEOP_ERASING_MEDIA       3263
#define IDS_ERASEOP_WAITING_VOLUME_REMOVAL 3264
#define IDS_ERASEOP_ERROR_ERASING       3265
#define IDS_ERASEOP_CANT_STOP           3266
#define IDS_ERASEOP_COMPLETE            3267
#define IDS_ERASEOP_ERASED_RESETTING    3268
#define IDS_OPERATION_STRINGS           3270
#define IDS_OPERATION_UPDATE            3270
#define IDS_OPERATION_COPY              3271
#define IDS_OPERATION_LOAD              3272
#define IDS_OPERATION_INVALID_OP        3273
#define IDS_OPERATION_ERASE             3274
#define IDS_OPERATION_REG_SCRUB         3275
#define IDS_OPFLAGS_OPTIONSTRINGS       3280
#define IDS_OPFLAGS_OPTIONSTRINGS_STATICID 3280
#define IDS_OPFLAGS_OPTIONSTRINGS_MULTI_STATICID 3281
#define IDS_OPFLAGS_OPTIONSTRINGS_FAT32 3282
#define IDS_OPFLAGS_OPTIONSTRINGS_WINCE 3283
#define IDS_OPFLAGS_OPTIONSTRINGS_ERASE 3284
#define IDS_OPMONITOR_MONITORING        3285
#define IDS_OPREGISTRY_SCRUBBING        3290
#define IDS_OPREGISTRY_SCRUB_COMPLETE   3291
#define IDS_OPREGISTRY_SCRUB_ERROR      3292
#define IDS_OPREGISTRY_SCRUB_NOTHING_TO_DO 3293
#define IDS_OPUPDATER_UPDATING          3295
#define IDS_OPUPDATER_SEARCHING_TO_RECOVER 3296
#define IDS_OPUPDATER_REQUIRES_RESET_RECOVERY 3297
#define IDS_OPUPDATER_SEARCHING_TO_UPDATE 3298
#define IDS_OPUPDATER_INVALID_DEVICE    3299
#define IDS_OPUPDATER_INVALID_STATE     3300
#define IDS_OPUPDATER_INVALID_MSG       3301
#define IDS_OPUPDATER_RESETTING_DEVICE  3302
#define IDS_OPUPDATER_LOADING_USBMSC    3303
#define IDS_OPUPDATER_LOADING_FIRMWARE  3304
#define IDS_OPUPDATER_COMPLETE          3305
#define IDS_OPUPDATER_UPDATE_ERROR      3306
#define IDS_OPUPDATER_ALLOCATING        3307
#define IDS_OPUPDATER_GET_DRIVE_SIZES   3308
#define IDS_OPUPDATER_WRITING_FILE      3309
#define IDS_PLAYERPROFILE_ERROR         3310
#define IDS_PROFILE_OK                  3311
#define IDS_PROFILE_WRN_INVALID_OPERATION 3312
#define IDS_PROFILE_ERR_FIRST_ERROR     3313
#define IDS_PROFILE_ERR_NOT_INITIALIZED 3314
#define IDS_PROFILE_ERR_NO_VALID_OPERATION 3315
#define IDS_PROFILE_ERR_NO_SELECTION    3316
#define IDS_PROFILE_ERR_MISSING_DIRECTORY 3317
#define IDS_PROFILE_ERR_MISSING_INI_FILE 3318
#define IDS_PROFILE_ERR_INVALID_CHARS   3319
#define IDS_PROFILE_ERR_INVALID_DESCRIPTION 3320
#define IDS_PROFILE_ERR_INVALID_USB_VENDOR_ID 3321
#define IDS_PROFILE_ERR_INVALID_USB_PROD_ID 3322
#define IDS_PROFILE_ERR_INVALID_SCSI_VENDOR_ID 3323
#define IDS_PROFILE_ERR_INVALID_SCSI_PROD_ID 3324
#define IDS_PROFILE_WRN_INVALID_VOLUME_LABLE 3325
#define IDS_PROFILE_MSG_OVERWRITE_PROMPT 3326
#define IDS_PROFILE_ERR_WRITE_FAILURE   3327
#define IDS_PROFILE_ERR_FILE_NO_EXIST   3328
#define IDS_OPUPDATER_VERIFYING_FILE    3329
#define IDS_PORTMGRDLG_DRIVES_TEXT      3330
#define IDS_PORTMGRDLG_PORT_GRP_TEXT    3331
#define IDS_OPUPDATER_LOADING_FILE      3332
#define IDS_PORTMGRDLG_PANEL_TEXT       3333
#define IDS_PORTMGRDLG_HUB_PORT_TEXT    3334
#define IDS_PORTMGRDLG_MONITORING       3335
#define IDS_PORTMGRDLG_COMPLETE         3336
#define IDS_OPUPDATER_INITIALIZING_DRM  3337
#define IDS_OPUPDATER_INITIALIZING_DATABASE 3338
#define IDS_PORTMGRDLG_FORMATTING       3339
#define IDS_REGSCRUB_CLEAN_TEXT         3340
#define IDS_REGSCRUB_REMOVE_STATIC_TEXT 3341
#define IDS_REGSCRUB_PROFILE_DESC_TEXT  3342
#define IDS_REGSCRUB_USB_VID_TEXT       3343
#define IDS_REGSCRUB_USB_PID_TEXT       3344
#define IDS_REGSCRUB_SCSI_VID_TEXT      3345
#define IDS_REGSCRUB_SCSI_PID_TEXT      3346
#define IDS_REGSCRUB_SCANNING_STATUS_TEXT 3347
#define IDS_REGSCRUB_DELETING_STATUS_TEXT 3348
#define IDS_REGSCRUB_ENTRIES_REM_STATUS_TEXT 3349
#define IDS_REGSCRUB_INVALID_PROFILE    3350
#define IDS_REGSCRUB_CONFIRM_PROMPT     3351
#define IDS_REGSCRUB_WRONG_OS           3352
#define IDS_REGSCRUB_FINISHED           3353
#define IDS_REGSCRUB_REMOVE_RECOVERY    3354
#define IDS_CFG_FNAME_TEXT              3360
#define IDS_CFG_DESC_TEXT               3361
#define IDS_CFG_DRIVE_TYPE_TEXT         3362
#define IDS_CFG_DRIVE_TAG_TEXT          3363
#define IDS_CFG_DRIVE_SIZE_TEXT         3364
#define IDS_CFG_DRIVE_DATA_GRP_TEXT     3365
#define IDS_CFG_ADD_DRIVE_TEXT          3366
#define IDS_CFG_DRIVES_GRP_TEXT         3367
#define IDS_CFG_SDK_BASE_TEXT           3368
#define IDS_OPLOADER_LOADING            3370
#define IDS_OPLOADER_LOAD_STARTED       3371
#define IDS_OPLOADER_COMPLETE           3372
#define IDS_OPLOADER_INVALID_DEVICE     3373
#define IDS_OPLOADER_INVALID_STATE      3374
#define IDS_OPLOADER_INVALID_MSG        3375
#define IDS_OPLOADER_LOADING_FIRMWARE   3376
#define IDS_OPLOADER_LOAD_ERROR         3378
#define IDS_STATUS_GRP_TEXT             3380
#define IDS_STATUS_PROFILE_TEXT         3381
#define IDS_STATUS_FW_VER_TEXT          3382
#define IDS_STATUS_START_TEXT           3383
#define IDS_STATUS_ELAPSED_TEXT         3384
#define IDS_STATUS_AVG_DURATION_TEXT    3385
#define IDS_STATUS_OK_UPDATES_TEXT      3386
#define IDS_STATUS_FAILED_UPDATES_TEXT  3387
#define IDS_STATUS_FAILURE_RATE_TEXT    3388
#define IDS_STATUS_NO_PORTS_SELECTED    3391
#define IDS_STATUS_NO_OPS_SELECTED      3392
#define IDS_STATUS_STATUS_TEXT          3393
#define IDS_CFG_USBPORT_MAX_PORTS       3394
#define IDS_CFG_CHANGES_LOST_WARNING    3500
#define IDS_ERROR_INVALID_DEVICE        5000
#define IDS_ERROR_DEVICE_REMOVED_DURING_OP 5001
#define IDS_ERROR_VOLUME_REMOVED_DURING_OP 5002
#define IDS_DEFINE_TABLE_TEXT           5003
#define IDS_OPUPDATE_HEADER_FILES       5004
#define IDS_OPUPDATE_HEADER_DESC        5005
#define IDS_OPUPDATE_HEADER_TYPE        5006
#define IDS_OPUPDATE_HEADER_TAG         5007
#define IDS_OPUPDATE_HEADER_SIZE        5008
#define IDS_OP_NAME_FOLDER              5009
#define IDS_COLUMN_FILENAME             5010
#define IDS_COLUMN_SIZE                 5011
#define IDS_COLUMN_TIMESTAMP            5012
#define IDS_NUM_OBJECTS                 5013
#define IDS_NEW_FOLDER                  5014
#define IDS_ADD_FOLDER                  5015
#define IDS_OP_COPY_STEP2               5016
#define IDS_HUB_REQUIRED                5017
#define IDS_UPDATE_STEP3_TEXT           5018
#define IDS_MENU_COPY_DRIVE             5019
#define IDS_UNAUTHORIZED_SYSTEM         5020
#define IDS_WAITING_TO_COMPLETE         5021
#define IDS_OTPOP_TEXT                  5022
#define IDS_OPERATION_OTP_REGISTER      5023
#define IDS_OPOTP_OP_FAILED             5024
#define IDS_OPOTP_WRITING_REG           5025
#define IDS_REGCHK_INFO_TEXT            5026
#define IDS_REGCHK_ENTRIES_TEXT         5027
#define IDS_REGCHK_OTHER_TEXT           5028
#define IDS_REGCHK_WARNING              5029
#define IDS_CFG_COM_PORT_MSGS           5030
#define IDR_DEFAULT_PROFILE_RESID_0     6000
#define IDR_DEFAULT_PROFILE_RESID_1     6001
#define IDR_DEFAULT_PROFILE_RESID_2     6002
#define IDR_DEFAULT_PROFILE_RESID_3     6003
#define IDR_OTPACCESS3700_RESID         6010
#define IDR_OTPACCESS3770_RESID         6011
#define IDR_OTPACCESS3780_RESID         6012
#define ID_OPTIONS_CONFIGURATION        32771
#define ID_START_STOP_TOGGLE            32772
#define ID_VIEW_LOG                     32773
#define ID_VIEW_S                       32774
#define ID_OPTIONS_CLEAN_REGISTRY       32775
#define ID_POPUP_SHOW_DETAILS           32776
#define IDM_ST_NEW                      32780
#define IDM_ST_EDIT                     32781
#define IDM_ST_DELETE                   32782
#define IDM_ST_MOVE_UP                  32783
#define IDM_ST_MOVE_DOWN                32784
#define IDM_ST_ADD_DIR                  32785
#define IDB_CLOSED_FOLDER               32786
#define IDB_FIRMWARE_FILE               32787
#define IDR_FILEOPLIST_MENU             32788
#define IDR_FOLDEROPLIST_MENU           32789
#define IDM_ST_COPY                     32790
#define IDR_RESID_UNKNOWN               -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
