%YAML 1.1
---
# Snapcraft Recipe for uuu (Universal Update Utility)
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
#
# Copyright (c) 2017 Snapcrafters
#

name: universal-update-utility
title: Universal Update Utility - UUU
summary: Freescale/NXP I.MX Chip image deploy tools
description: |
  **Key features**

  - The real cross platform. Linux, Windows, MacOS(not test yet)
  - Multi devices program support
  - Daemon mode support
  - Few depedencies (only libusb, zlibc, libbz2)
  - Firmware (uboot/kernel) uses WCID to auto load the winusb driver
    on the Windows side. Windows7 users need to install the winusb driver
    from [https://zadig.akeo.ie/](https://zadig.akeo.ie/) Windows10 will
    install the driver automatically.

  **Search keywords**

  mfgtools, uuu, nxp, nxpmicro
icon: snap/gui/universal-update-utility.png
license: BSD-3-Clause
adopt-info: main
assumes:
  - command-chain
  # required by the `snapctl is-connected` command
  - snapd2.43
base: core18
confinement: strict
grade: stable

parts:
  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*

  # Bash completion snippets
  bash-completion:
    source: snap/local/bash-completion
    plugin: dump
    organize:
      '*': bash-completion/

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v2.0.2
    plugin: dump
    build-packages:
      - curl
      - jq
      - sed

      - git
    stage:
      - scriptlets/selective-checkout
    prime:
      - -*

  main:
    after:
      - selective-checkout

    source: .
    source-depth: 50
    override-pull: |
      set -o nounset

      snapcraftctl pull

      "${SNAPCRAFT_STAGE}"/scriptlets/selective-checkout \
        --release-tag-pattern='uuu_[[:digit:]]+(\.[[:digit:]]+){2}' \
        --release-tag-prefix=uuu_
    build-snaps:
      - cmake
    build-packages:
      # CMake shipped in Ubuntu 18.04(3.10.2) is too old
      #- cmake
      - g++
      - libbz2-dev
      - libusb-1.0-0-dev
      - libssl-dev
      - pkg-config
    plugin: cmake
    stage-packages:
      - libbz2-1.0
      - libusb-1.0-0
      - libssl1.0.0
    filesets:
      docs-copyright:
      - usr/share/doc/*/copyright

      executables:
      - bin/*

      library-shared:
      - lib/**/*.so*
    prime:
      - $docs-copyright
      - $executables
      - $library-shared

apps:
  universal-update-utility:
    adapter: full
    command: bin/uuu
    command-chain:
      - bin/universal-update-utility-launch
    completer: bash-completion/universal-update-utility
    environment:
      # Snap runtime only ship C.UTF-8 locale
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

plugs:
  # Regular files access
  home:
    # Allow reading the SUDO_USER's uuu script when run as root
    # (by default only scripts under root's home dir is readable)
    read: all
  removable-media: # Non-A/C

  # NOTE: This only lifts the snapd side of confinement, the user still
  #       require classic read/write access to the target device node
  raw-usb:

  network-bind:
